### ISSUE TITLE
HTTP的生命周期

### ISSUE THREAD

**Issue by ylxdzsw** [HIT-Alibaba/interview#1]
HTTP的生命周期是shen me gui
我今天就被问到了。。当时我就懵逼了。。
快加进去吧以免学弟们也挂在这里

**Comment by skyline75489** [comment]
我也是第一次听说这个，想加内容的话可以直接修改

**Comment by ylxdzsw** [comment]
我搜了好久根本没搜到，是不是面试官问错了←_←

**Comment by dodola** [comment]
面试的是服务器端开发？查到了这篇文章。
http://tia.mat.br/blog/html/2014/10/06/life_of_a_http_request.html

**Comment by jasonlvhit** [comment]
这种问题直接由下往上扯，从SYN，ACK队列扯到TCP字节流之后扯到SSL层再扯HTTP协议，再顺便扯点telnet，SMTP啥啥的应用层协议，往深点说，问这种xiudou问题的面试官直接就懵逼了，，，，，

**Comment by abbshr** [comment]
@ylxdzsw 求看简历

**Comment by ylxdzsw** [comment]
@dodola 赞，看着像，不过不确定是不是面试官想要的
@jasonlvhit 扯这么多面试官不懂的他会不会认为你是不知道答案故意绕开话题啊。。
@abbshr 发到这里怕被爬虫爬掉手机然后天天法X功骚扰，私发给你吧

**Comment by winlandiano** [comment]
@jasonlvhit 好顶赞

**Comment by MaybeMercy** [comment]
666666
