### ISSUE TITLE
当重载父类中的属性时，父类和子类均会生成 set 和 get 方法

### ISSUE THREAD

**Issue by sunbohong** [HIT-Alibaba/interview#12]
在 https://github.com/HIT-Alibaba/interview/blob/master/source/iOS/ObjC-Basic/Class.md#synthesize-和-dynamic 中提到 “当重载父类中的属性时，也必须手动写 synthesize”，但是，通过查看 Xcode 7.0 编译下面的代码，却发现 “当重载父类中的属性时，父类和子类均会生成 `setName` 和 `name` 两个方法”

```
@interface Father : NSObject

@property NSString *name;

@end

@implementation Father

@end

@interface Son : NSObject

@property NSString *name;

@end

@implementation Son

@end
```

**Comment by skyline75489** [comment]
这部分的内容来源于 https://stackoverflow.com/questions/19784454/when-should-i-use-synthesize-explicitly 这个答案，可能内容有些老了。随时欢迎 PR。

**Comment by skyline75489** [comment]
不过你这个代码里 Son 貌似没有继承 Father 啊。。。

**Comment by sunbohong** [comment]
是我犯低级错误了。

因为对“当重载父类中的属性时，也必须手动写 synthesize”有些记忆模糊，所以没有 PR。
