### ISSUE TITLE
关于 layoutSubviews 被调用的时机

### ISSUE THREAD

**Issue by sunbohong** [HIT-Alibaba/interview#18]
http://hit-alibaba.github.io/interview/iOS/Cocoa-Touch/UIView-Basic.html
提到“addSubview 会导致 ……， 同时 add 的 target view 以及它所有的子 view 都会被调用”
但是根据我的测试结果，默认情况下，子 view 的 `layoutSubviews` 方法没有被调用。

**Comment by skyline75489** [comment]
这部分参考的也是 SO 上的一篇答案 http://stackoverflow.com/questions/728372/when-is-layoutsubviews-called#

下面有一个人的回答其实澄清了这一点，就是 addSubview 还和 autoresizing mask 有关，因此并不是所有的 addSubview 都会导致 layoutSubviews

**Comment by skyline75489** [comment]
加入说明

**Comment by michaelLeeGDUT** [comment]
根据我的测试结果，addSubview 还和 autoresizing mask 没关系，调用addSubview之后并不会调用被add的view的layoutSubviews方法。
