### ISSUE TITLE
四个全局队列

### ISSUE THREAD

**Issue by yisimeng** [HIT-Alibaba/interview#23]
https://hit-alibaba.github.io/interview/iOS/Cocoa-Touch/Multithreading.html#自己创建的队列与系统队列有什么不同？

这里第一句说“最终会把任务分配到系统提供的主队列和四个全局的串行队列上”，四个全局队列是并行的
搜了下api：
@function dispatch_get_global_queue
 * Returns a well-known global concurrent queue of a given quality of service class.

**Comment by skyline75489** [comment]
所以问题是？。。。

**Comment by yisimeng** [comment]
所以是不是改成并行队列

**Comment by skyline75489** [comment]
奥，是写错了，我改下
