### ISSUE TITLE
您好，发现了一个错误

### ISSUE THREAD

**Issue by cuikun** [HIT-Alibaba/interview#27]
在响应者链一节中，根据Apple[官方文档](https://developer.apple.com/documentation/uikit/understanding_event_handling_responders_and_the_responder_chain)的描述，在UIApplication之后，事件会传给UIApplicationDelegate。![图片](https://docs-assets.developer.apple.com/published/7c21d852b9/f17df5bc-d80b-4e17-81cf-4277b1e0f6e4.png)

**Comment by Artoria-Huang** [comment]
确实是

**Comment by skyline75489** [comment]
UIApplicationDelegate 是一个 protocol，实际的对象仍然是 UIApplication。这里的描述我认为是 OK 的
