### ISSUE TITLE
The AlertDialog pops up is doesn't call onPause method

### ISSUE THREAD

**Issue by yangyouqian** [HIT-Alibaba/interview#29]
Android Document：
void onPause ()
Called as part of the activity lifecycle when an activity is going into the background, but has not (yet) been killed. The counterpart to onResume().

When activity B is launched in front of activity A, this callback will be invoked on A. B will not be created until A's onPause() returns, so be sure to not do anything lengthy here.

**Android开发-Android基础-Activity/Service生命周期**
onPause方法中说到:AlertDialog等弹出窗口时它（Activity）处于暂停状态。只是new出来的对话框是不会调用onPause方法的。

**Comment by winlandiano** [comment]
确实是这样，需要修改
