### ISSUE TITLE
请求更新 Gitbook

### ISSUE THREAD

**Issue by hangim** [HIT-Alibaba/interview#33]
https://hit-alibaba.github.io/interview/basic/network/IP.html

IP地址这一页，`4.指向所有子网的广播` 下面的 `广播示例` 部分无法正常显示

而看下面这个链接里面是正常的

https://github.com/HIT-Alibaba/interview/blob/master/source/basic/network/IP.md

猜测可能是没及时更新所致

**Comment by skyline75489** [comment]
这个还真不是，这个是 Gitbook 的 MD 渲染的问题......

**Comment by skyline75489** [comment]
我改一下吧。Thanks.
