### ISSUE TITLE
TLS应该是非对称加密算法

### ISSUE THREAD

**Issue by SimonTart** [HIT-Alibaba/interview#35]
`HTTP over TLS `这一节中原文
> 从上面的过程可以看到，TLS 的完整过程需要三个算法（协议），密钥交互算法，对称加密算法，和消息认证算法（TLS 的传输会使用 MAC(message authentication code) 进行完整性检查）。

TLS应该是一种非对称加密算法。
参考资料: [TLS/SSL](https://zh.wikipedia.org/wiki/%E5%82%B3%E8%BC%B8%E5%B1%A4%E5%AE%89%E5%85%A8%E6%80%A7%E5%8D%94%E5%AE%9A)

**Comment by skyline75489** [comment]
TLS 不是一个“算法”，而是一个协议。请仔细阅读

**Comment by SimonTart** [comment]
@skyline75489 
是的我的表述不准确，我的理解是：TLS是一种协议，协议中使用了非对称加密算法。我感觉原文这里说需要`对称加密算法`是有问题的。

**Comment by skyline75489** [comment]
你说的“非对称加密算法”就是我提到的“密钥交互算法”，“对称加密算法”用于握手完成之后的通信

**Comment by SimonTart** [comment]
@skyline75489  感谢你的耐心回答，是我没理解清楚原文意思。
